### PR TITLE
Fixed #129: Spelling mistake in FAQ section

### LINKED ISSUE #129: Spelling mistake in FAQ section
**Describe the bug**
Spelling mistake in the FAQ page where "ReactJs is spelt as "RaectJs"

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the faq section
2. Click on "Can I use anything other than React?"
3. The error is present in the answer.

**Expected behaviour**
The spelling must be "ReactJs"

**Screenshots**
Screenshot 2023-01-31 at 11 49 49 AM

### PR DESCRIPTION
**Pull request by ashrrithk**
Fixed #129 

Screenshot 2023-01-31 at 12 57 59 PM

### CODE REVIEW

File: services/metadata/twoplaysamonth.js [hunk 1]
```diff
@@ -1,7 +1,8 @@
 export const Config = {
   name: "twoplaysamonth",
   display: "#2PlaysAMonth",
-  description: "#2PlaysAMonth is an event by ReactPlay for the ReactJs community to learn, build, share in public. Join us.",
+  description:
```
Comment (atapas) [inline services/metadata/twoplaysamonth.js:4]: Can we ignore this new line?

Comment (ashrrithk) [reply services/metadata/twoplaysamonth.js:4]: Sure, I'll fix that. It happened due to my VS Code formatter

Comment (ashrrithk) [reply services/metadata/twoplaysamonth.js]: I removed the new line

**Review by atapas — APPROVED** [review]
